# run on container-based infrastructure
sudo: false

language: python

addons:
    apt:
        packages:
            - gfortran

env:
  global:
    - OPENRADAR_BUILD_DIR=$TRAVIS_BUILD_DIR
    # openradar-bot
    # todo: add secure env var
    # - secure:

matrix:
    include:
    - python: 2.7
      env:
        - PYTHON_VERSION="2.7"
        - DOC_BUILD="true"
    - python: 3.5
      env:
        - PYTHON_VERSION="3.5"
    - python: 3.6
      env:
        - PYTHON_VERSION="3.6"

install:
    - deactivate
    - source scripts/install.sh
    - scripts/install_wradlib.sh

before_script:
    - export OPENRADAR_DATA=$HOME/openradar-data
    # duplicate notebooks folder
    - export OPENRADAR_NOTEBOOKS=$OPENRADAR_BUILD_DIR/notebooks-render
    - mkdir $OPENRADAR_NOTEBOOKS && cp -R notebooks $OPENRADAR_NOTEBOOKS/
    # enter headless mode
    - export DISPLAY=:99
    - sh -e /etc/init.d/xvfb start
    - sleep 3

script:
    - scripts/execute_notebooks.sh

after_success:
    - if [[ "$DOC_BUILD" == "true" ]]; then scripts/copy_notebooks.sh; fi
    - if [[ "$DOC_BUILD" == "true" ]]; then cd $OPENRADAR_BUILD_DIR; scripts/build_docs.sh; fi
